services:
  ml:
    build:
      context: ./backend/ml-service
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - ml
    environment:
      ML_GRPC_ADDRESS: ml:50051
      CORE_HTTP_ADDRESS: 0.0.0.0:8080
      CORE_GRPC_ADDRESS: 0.0.0.0:50052
    ports:
      - "8080:8080"
      - "50052:50052"
