config setup
    uniqueids=no
conn lab
    keyexchange=ikev2
    type=transport
    authby=psk
    left=fd00:31::2
    leftid=@left
    right=fd00:31::3
    rightid=@right
    ike=aes128-sha256-modp2048!
    esp=aes128-sha256-modp2048!
    mobike=no
    forceencaps=no
    rekey=no
    reauth=no
    dpdaction=none
    auto=add
