"use client";
/* Health polling is the intentional fallback while Core event streaming is not browser-exposed. */
/* eslint-disable react-hooks/set-state-in-effect */

import { ChangeEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../components/app-shell";

type Health = { live: boolean; ready: boolean; status: string; dependencies: Record<string, string> };
type Upload = { source_id: string; filename: string; packets: number; bytes: number; ike_packets: number; esp_packets: number; ah_packets: number; nat_t_packets: number };
const bytes = (value?: number) => { const n = Number(value ?? 0); if (!n) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const i = Math.min(Math.floor(Math.log(n) / Math.log(1024)), 3); return `${(n / 1024 ** i).toFixed(i ? 1 : 0)} ${units[i]}`; };

export default function WorkspacePage() {
  const router = useRouter(); const [health, setHealth] = useState<Health | null>(null); const [file, setFile] = useState<File | null>(null); const [upload, setUpload] = useState<Upload | null>(null); const [busy, setBusy] = useState(false); const [enableML, setEnableML] = useState(true); const [message, setMessage] = useState("Choose a classic PCAP to start a new evidence ledger.");
  const refresh = useCallback(async () => { try { setHealth(await (await fetch("/api/backend-status", { cache: "no-store" })).json()); } catch { setHealth(null); } }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, [refresh]);
  const api = async <T,>(url: string, init?: RequestInit): Promise<T> => { const response = await fetch(`/api/core${url}`, { ...init, cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Request failed"); return body as T; };
  const uploadPCAP = async () => { if (!file) return; setBusy(true); setMessage("Validating capture and building packet counters…"); try { const data = new FormData(); data.set("pcap", file); const source = await api<Upload>("/v1/pcap", { method: "POST", body: data }); setUpload(source); setMessage("Capture is ready. Review the observed traffic and start analysis."); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } };
  const begin = async () => { if (!upload) return; setBusy(true); const useML = enableML && health?.dependencies.ml === "READY"; setMessage("Creating the analysis workspace…"); try { const result = await api<{ analysis_id: string }>("/v1/analyses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source_id: upload.source_id, enable_ml: useML }) }); router.push(`/analysis/${result.analysis_id}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Analysis could not start."); setBusy(false); } };
  const mlReady = health?.dependencies.ml === "READY";
  return <AppShell><main className="view-main workspace-main"><header className="page-heading"><p>New workspace</p><h1>Start with what you can prove.</h1><span>Upload a classic PCAP. The Core will observe IPsec metadata, build flow features, fuse evidence, and run the selected deterministic checks.</span></header><section className="workspace-grid"><article className="surface-panel upload-card"><div className="step-label">01 · Capture input</div><h2>Bring a classic PCAP</h2><p>`.pcap` and `.cap` are accepted. Convert PCAPNG first with `editcap -F libpcap input.pcapng output.pcap`.</p><label className="drop-zone"><input type="file" accept=".pcap,.cap,application/vnd.tcpdump.pcap" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} /><b>{file ? file.name : "Choose a PCAP file"}</b><span>{file ? `${bytes(file.size)} · ready to validate` : "Classic libpcap format only"}</span></label><button className="primary-button" disabled={!file || busy} onClick={() => void uploadPCAP()}>{busy ? "Working…" : upload ? "Validate another capture" : "Validate capture"}</button>{upload && <div className="upload-metrics"><span><b>{upload.packets.toLocaleString()}</b> packets</span><span><b>{upload.ike_packets.toLocaleString()}</b> IKE</span><span><b>{upload.esp_packets.toLocaleString()}</b> ESP</span><span><b>{bytes(upload.bytes)}</b> size</span></div>}</article><article className="surface-panel readiness-card"><div className="step-label">02 · Analysis choices</div><h2>Choose the evidence sources</h2><div className="readiness-line"><div><b>Go Core</b><span>Protocol, Fusion, security, reports</span></div><Status ready={Boolean(health?.live)} text={health?.status ?? "checking"} /></div><div className="readiness-line"><div><b>ML worker</b><span>Optional encrypted-flow classification</span></div><Status ready={mlReady} text={mlReady ? "ready" : "unavailable"} /></div><label className={`toggle-row ${mlReady ? "" : "disabled"}`}><input type="checkbox" checked={enableML} disabled={!mlReady || busy} onChange={event => setEnableML(event.target.checked)} /><span><b>Include ML inference</b><small>UNKNOWN remains an abstention, not an error.</small></span></label><button className="primary-button full" disabled={!upload || busy} onClick={() => void begin()}>{busy ? "Starting…" : "Create analysis workspace →"}</button></article></section><section className="workspace-note"><span className="pulse" /><div><b>Passive by design</b><p>ESP payloads are never decrypted. Unavailable VICI, XFRM, ML, or SHAP evidence remains explicit in the final ledger.</p></div></section><p className="workspace-message">{message}</p></main></AppShell>;
}
function Status({ ready, text }: { ready: boolean; text: string }) { return <span className={`status-pill ${ready ? "good" : "warn"}`}>{text}</span>; }
