# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.ml.v1 import traffic_classifier_pb2 as proto_dot_ml_dot_v1_dot_traffic__classifier__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/ml/v1/traffic_classifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrafficClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictTraffic = channel.unary_unary(
                '/sih.ipsec.ml.v1.TrafficClassifier/PredictTraffic',
                request_serializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.FlowFeatures.SerializeToString,
                response_deserializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.PredictionResult.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sih.ipsec.ml.v1.TrafficClassifier/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.HealthStatus.FromString,
                _registered_method=True)


class TrafficClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictTraffic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictTraffic': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTraffic,
                    request_deserializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.FlowFeatures.FromString,
                    response_serializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.PredictionResult.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sih.ipsec.ml.v1.TrafficClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sih.ipsec.ml.v1.TrafficClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrafficClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictTraffic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sih.ipsec.ml.v1.TrafficClassifier/PredictTraffic',
            proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.FlowFeatures.SerializeToString,
            proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.PredictionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sih.ipsec.ml.v1.TrafficClassifier/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_ml_dot_v1_dot_traffic__classifier__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
