import Link from "next/link";
import { LandingFooter } from "@/components/ui/site-chrome";
import { LiveAnalysisPanel } from "@/components/dashboard/live-analysis-panel";

type View = {
  title: string;
  eyebrow: string;
  description: string;
  availability: "AVAILABLE" | "ADAPTER REQUIRED";
  cards: Array<[string, string, string]>;
};

const navigation = [
  ["overview", "OVERVIEW"], ["upload", "UPLOAD / LIVE"], ["progress", "ANALYSIS PROGRESS"],
  ["sessions", "VPN SESSIONS"], ["flows", "FLOWS"], ["classification", "TRAFFIC CLASSIFICATION"],
  ["evidence", "EVIDENCE & PROVENANCE"], ["findings", "SECURITY FINDINGS"], ["risk", "RISK MATRIX"],
  ["gateway", "GATEWAY VERIFICATION"], ["reports", "REPORTS"], ["health", "SYSTEM HEALTH"],
] as const;

const views: Record<string, View> = {
  overview: { title: "Evidence overview", eyebrow: "WORKSPACE / OVERVIEW", description: "A clear summary of available IPsec evidence. Values below are sample presentation data until a completed analysis is selected.", availability: "AVAILABLE", cards: [["OVERALL RISK", "NOT CALCULATED", "Deterministic assessment is waiting for an analysis."], ["EVIDENCE COVERAGE", "NO WORKSPACE", "Upload a PCAP to establish observed and derived coverage."], ["ML WORKER", "CHECK ON ANALYSIS", "ML is optional and remains distinctly INFERRED."], ["GATEWAY", "UNAVAILABLE", "Authorized Deep Assessment is required for gateway facts."]] },
  upload: { title: "Input and capture", eyebrow: "WORKSPACE / INPUT", description: "The browser-supported workflow accepts classic PCAP or CAP files and starts offline passive analysis.", availability: "AVAILABLE", cards: [["PASSIVE PCAP", "AVAILABLE", "Upload and analyse a classic PCAP."], ["PCAPNG", "CONVERT FIRST", "The current API accepts classic PCAP/CAP."], ["PASSIVE LIVE", "ADAPTER REQUIRED", "No browser capture orchestration endpoint exists."], ["DEEP ASSESSMENT", "ADAPTER REQUIRED", "Requires explicit authorization and local sensor support."]] },
  progress: { title: "Analysis progress", eyebrow: "LIFECYCLE / PIPELINE", description: "Operational progress is polled from the Go Server for a running offline analysis.", availability: "AVAILABLE", cards: [["OBSERVE", "PENDING", "Packet observations begin after source upload."], ["DERIVE", "PENDING", "Deterministic protocol and flow facts."], ["INFER", "OPTIONAL", "Metadata-only ML, never protocol truth."], ["ASSESS", "PENDING", "Deterministic findings and risk score."]] },
  sessions: { title: "VPN session explorer", eyebrow: "PROTOCOL / IKE · ESP · AH", description: "Session details are available only as aggregate insights after a completed analysis.", availability: "ADAPTER REQUIRED", cards: [["IKE SESSIONS", "NO ANALYSIS", "Run a PCAP analysis to inspect aggregate protocol data."], ["ESP SPI", "OBSERVED", "Packet SPI values are observation-only."], ["SECURITY ASSOCIATIONS", "PARTIAL API", "Individual session routes and filters are not exposed."], ["NAT-T", "UNKNOWN", "Shown only when supported by captured traffic."]] },
  flows: { title: "Metadata flow explorer", eyebrow: "FLOW WINDOWS / NO PAYLOAD", description: "ESP payloads are never decrypted. Browser flow-window detail endpoints are not registered yet.", availability: "ADAPTER REQUIRED", cards: [["FLOW LIST", "UNAVAILABLE", "Needs a browser flow-list adapter."], ["WINDOW SIZE", "10 SECONDS", "Documented metadata aggregation interval."], ["DIRECTIONALITY", "DERIVED", "Available only when analysis supplies aggregate facts."], ["PAYLOAD", "NEVER EXPOSED", "Encrypted ESP payload is outside this product."]] },
  classification: { title: "Traffic classification", eyebrow: "ML / METADATA ONLY", description: "Model output is probabilistic context and is always marked INFERRED—not protocol evidence or a security finding.", availability: "ADAPTER REQUIRED", cards: [["FINAL CLASS", "UNKNOWN", "No supported conclusion before a model result."], ["CONFIDENCE", "UNAVAILABLE", "Shown only from Go-owned ML results."], ["TOP CANDIDATES", "UNAVAILABLE", "Candidates remain context when final output is UNKNOWN."], ["EXPLANATIONS", "OPTIONAL", "Feature attributions may be unavailable."]] },
  evidence: { title: "Evidence and provenance", eyebrow: "SOURCE / STATUS / CONFIDENCE", description: "Every security-relevant value carries its evidence status. Detail filtering and evidence-chain APIs require an adapter.", availability: "ADAPTER REQUIRED", cards: [["OBSERVED", "PACKET FACTS", "Directly present in captured traffic."], ["DERIVED", "DETERMINISTIC", "Computed from observations."], ["INFERRED", "ML OUTPUT", "Probabilistic metadata classification."], ["VERIFIED GATEWAY", "AUTHORIZED ONLY", "Never shown for passive PCAP."]] },
  findings: { title: "Security findings", eyebrow: "DETERMINISTIC ASSESSMENT", description: "Findings originate from deterministic Go security rules. They are not generated from ML classifications.", availability: "ADAPTER REQUIRED", cards: [["ASSESSMENT", "NOT RUN", "Complete an analysis to receive findings."], ["CRITICAL", "—", "No sample severity is presented as a real result."], ["REMEDIATION", "UNAVAILABLE", "Available when linked to a deterministic finding."], ["COVERAGE", "PARTIAL", "Unavailable sources are not passing results."]] },
  risk: { title: "Risk score and threat matrix", eyebrow: "DETERMINISTIC / EXPLAINABLE", description: "Risk is a deterministic score, separate from ML confidence. No score is displayed before assessment finishes.", availability: "ADAPTER REQUIRED", cards: [["RISK SCORE", "NOT CALCULATED", "The deterministic engine has not completed."], ["THREAT MATRIX", "UNAVAILABLE", "Available from aggregate insights when present."], ["SCORE DRIVERS", "UNAVAILABLE", "Needs a documented browser mapping."], ["COVERAGE IMPACT", "VISIBLE", "Missing data reduces coverage, not risk."]] },
  gateway: { title: "Gateway verification", eyebrow: "AUTHORIZED DEEP ASSESSMENT", description: "Gateway facts require explicit authorized Deep Assessment mode and gateway provenance.", availability: "ADAPTER REQUIRED", cards: [["MODE", "PASSIVE PCAP", "Current browser workflow does not authorize Deep Assessment."], ["VICI", "UNAVAILABLE", "Local gateway adapter is not browser-exposed."], ["XFRM", "UNAVAILABLE", "Local gateway adapter is not browser-exposed."], ["VERIFIED FACTS", "NONE DISPLAYED", "Passive observations are never labelled gateway verified."]] },
  reports: { title: "Reports and exports", eyebrow: "EXECUTIVE PDF", description: "Generate an executive PDF after an analysis completes. Technical and JSON export options need backend support.", availability: "AVAILABLE", cards: [["EXECUTIVE PDF", "AVAILABLE AFTER ANALYSIS", "The Go Server generates and serves the PDF."], ["TECHNICAL EXPORT", "ADAPTER REQUIRED", "Selectable report formats are not implemented."], ["JSON EXPORT", "ADAPTER REQUIRED", "No browser export endpoint is registered."], ["EVIDENCE LABELS", "PRESERVED", "Reports must retain evidence provenance."]] },
  health: { title: "System health", eyebrow: "DEPENDENCY STATUS", description: "The Go Server health endpoint is browser-accessible. ML and sensor availability must be shown without pretending they are healthy.", availability: "AVAILABLE", cards: [["GO SERVER", "CHECKING", "Refresh status from the /health endpoint."], ["ML WORKER", "CHECK ON ANALYSIS", "The browser never calls Python directly."], ["FUSION", "CHECK ON ANALYSIS", "Aggregate insight availability is best effort."], ["LOCAL SENSOR", "UNAVAILABLE", "Browser readiness adapter is not registered."]] },
};

function StatusBadge({ status }: { status: View["availability"] }) { return <span className={`border px-2 py-1 text-[9px] font-bold tracking-[.12em] ${status === "AVAILABLE" ? "border-teal-300/60 text-teal-200" : "border-amber-300/60 text-amber-200"}`}>{status}</span>; }

export function DashboardShell({ view = "overview" }: { view?: string }) {
  const current = views[view] ?? views.overview;
  return <div className="min-h-svh bg-black font-mono text-white"><nav className="flex gap-2 overflow-x-auto border-b border-white/15 bg-black px-5 py-3 lg:hidden" aria-label="Dashboard navigation">{navigation.map(([slug, label]) => <Link key={slug} href={slug === "overview" ? "/dashboard" : `/dashboard/${slug}`} className={`shrink-0 border px-3 py-2 text-[9px] tracking-[.1em] ${slug === view ? "border-teal-200 bg-teal-200 text-slate-950" : "border-white/20 text-white/60"}`}>{label}</Link>)}</nav><div className="mx-auto flex max-w-[1600px]">
    <aside className="hidden w-64 shrink-0 border-r border-white/10 bg-[#0d1320] px-4 py-8 lg:block"><p className="px-3 text-[10px] font-bold tracking-[.16em] text-white/40">IPSEC SENTINEL TWIN</p><nav className="mt-7 grid gap-1" aria-label="Dashboard navigation">{navigation.map(([slug, label]) => <Link key={slug} href={slug === "overview" ? "/dashboard" : `/dashboard/${slug}`} className={`border-l px-3 py-2.5 text-[10px] tracking-[.11em] transition ${slug === view ? "border-teal-300 bg-white/[.06] text-teal-200" : "border-transparent text-white/55 hover:border-white/30 hover:bg-white/[.03] hover:text-white"}`}>{label}</Link>)}</nav><div className="mt-10 border-t border-white/10 pt-5 text-[9px] leading-6 text-white/45">OBSERVED · DERIVED<br />INFERRED · VERIFIED_GATEWAY<br />UNKNOWN · UNAVAILABLE</div></aside>
    <main className="min-w-0 flex-1 px-5 py-10 sm:px-8 lg:px-12"><div className="border-l border-dashed border-white/35 pl-5"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 pb-7"><div><p className="text-[10px] font-bold tracking-[.16em] text-teal-200/80">{current.eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-[.06em] sm:text-4xl">{current.title.toUpperCase()}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/60">{current.description}</p></div><StatusBadge status={current.availability} /></div></div>
      <div className="mt-7 flex flex-wrap gap-2 border-y border-white/10 py-4 text-[10px] text-white/45"><span className="border border-white/15 px-3 py-2">WORKSPACE: NONE SELECTED</span><span className="border border-white/15 px-3 py-2">MODE: PASSIVE PCAP</span><span className="border border-white/15 px-3 py-2">GO SERVER: CHECK ON WORKSPACE</span></div>
      <LiveAnalysisPanel />
      <div className="mt-7 grid border-l border-t border-white/15 sm:grid-cols-2 xl:grid-cols-4">{current.cards.map(([label, value, body]) => <article key={label} className="min-h-44 border-b border-r border-white/15 bg-white/[.018] p-5 transition duration-300 hover:bg-white/[.055]"><p className="text-[10px] tracking-[.13em] text-white/45">{label}</p><h2 className="mt-8 text-lg font-bold tracking-[.06em] text-teal-100">{value}</h2><p className="mt-3 text-xs leading-6 text-white/55">{body}</p></article>)}</div>
      <section className="mt-7 border border-white/15 bg-white/[.025] p-6"><p className="text-[10px] font-bold tracking-[.14em] text-white/45">EVIDENCE SAFETY NOTE</p><p className="mt-3 max-w-4xl text-sm leading-7 text-white/65">The dashboard distinguishes direct packet observations, deterministic derivations, ML inference, authorized gateway verification, unknown conclusions, and unavailable sources. ESP payloads are never decrypted or displayed.</p>{view === "upload" && <Link href="/workspace" className="mt-5 inline-block border border-teal-200 bg-teal-200 px-4 py-2 text-[10px] font-bold tracking-[.12em] text-slate-950 transition hover:bg-transparent hover:text-teal-100">OPEN PCAP WORKSPACE</Link>}</section>
    </main></div><LandingFooter /></div>;
}
