import { securityScorePresentation } from "./security-score";

type Finding = {Title?: string; Severity?: string; Description?: string; Recommendation?: string; RuleID?: string; EvidenceProperties?: string[]};
export function RiskCards({value}: {value: unknown}) {
 const a = (value ?? {}) as {score?: number; grade?: string; findings?: Finding[]; unknown_evidence_count?: number};
 const presentation = securityScorePresentation(a);
 if (presentation.assessedScore === undefined) return <p className="mt-5 text-white/50">Security assessment is not available yet.</p>;
 return <section className="my-6 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><article className={`border p-5 ${presentation.isProvisional ? "border-amber-200/35" : "border-teal-200/25"}`}><p className="text-xs text-white/50">Security posture</p><p className={`mt-3 text-3xl ${presentation.isProvisional ? "text-amber-100" : "text-teal-100"}`}>{presentation.assessedScore}/100</p>{presentation.isProvisional && <p className="mt-3 text-xs text-white/50">Score based on the research data available.</p>}</article><article className="border border-white/15 p-5"><p className="text-xs text-white/50">Findings</p><p className="mt-3 text-3xl">{a.findings?.length ?? 0}</p></article><article className="border border-white/15 p-5"><p className="text-xs text-white/50">Configuration evidence coverage</p><p className="mt-3 text-3xl">{presentation.coveragePercent === undefined ? "Unavailable" : `${presentation.coveragePercent}%`}</p><p className="mt-3 text-xs text-white/50">{presentation.unknownEvidence ?? "Unknown"} of 6 critical facts unavailable</p></article></div><p className="text-xs leading-6 text-white/50">The score reflects the checks supported by the research data. Review configuration evidence coverage before relying on the assessment.</p>{!a.findings?.length && <p className="text-sm text-white/60">No findings were raised from the available evidence.</p>}{a.findings?.map((f,i)=><article key={f.RuleID ?? i} className="border border-amber-200/25 p-5"><p className="text-xs text-amber-200">{f.Severity} · {f.RuleID}</p><h3 className="mt-3 text-lg">{f.Title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{f.Description}</p><div className="mt-4 border-l-2 border-teal-200 pl-4"><p className="text-xs text-teal-100">HOW TO FIX</p><p className="mt-2 text-sm leading-6">{f.Recommendation ?? "No recommendation supplied."}</p></div><p className="mt-3 text-xs text-white/40">Evidence: {f.EvidenceProperties?.join(", ") ?? "Not supplied"}</p></article>)}</section>;
}
